<?php

/**
 * @file
 * Contains ninghao_ui.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_page_attachments_alter().
 */
function ninghao_ui_page_attachments_alter(array &$attachments) {
  $attachments['#attached']['library'][] = 'ninghao_ui/ui.button';
  // Remove some meta tags.
  $meta_tags = array('system_meta_generator');
  foreach ($attachments['#attached']['html_head'] as $key => $value) {
    if (in_array($value[1], $meta_tags)) {
      unset($attachments['#attached']['html_head'][$key]);
    }
  }

  if (_ninghao_ui_is_access_devel_info()) {
    $attachments['#attached']['library'][] = 'ninghao_ui/ui.devel';
  }
  // dpm($attachments);
}

/**
 * Implementation of hook_element_info_alter().
 */
function ninghao_ui_element_info_alter(array &$info) {
  dpm($info);
  if (isset($info['submit'])) {
    $info['submit']['#attributes']['class'][] = 'ui';
  }
}

/**
 * Check if current user has "access devel information" access.
 */
function _ninghao_ui_is_access_devel_info() {
  $user = \Drupal::currentUser();
  return $user->hasPermission('access devel information');
}

/**
 * Implements hook_help().
 */
function ninghao_ui_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ninghao_ui module.
    case 'help.page.ninghao_ui':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom UI fro back and front.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ninghao_ui_theme() {
  return [
    'ninghao_ui' => [
      'template' => 'ninghao_ui',
      'render element' => 'children',
    ],
  ];
}
